# Generated by Django 5.2.4 on 2025-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_criteria_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('wating', "Ko'rib chiqilmoqda"), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
