# Generated by Django 5.2.4 on 2025-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting', "Ko'rib chiqilmoqda"), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='waiting', max_length=100),
        ),
    ]
