# Generated by Django 5.2.4 on 2026-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='criteria',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='file',
            new_name='certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='diploma',
            field=models.FileField(default=1, upload_to='applications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='fio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.FileField(default=1, upload_to='applications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
