# Generated by Django 5.2.4 on 2026-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_application_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='diploma_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
