# Generated by Django 5.2.4 on 2026-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_application_diploma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
